package rql

import (
	"errors"
	"fmt"
	"strconv"
)

// Parser is the parser for RQL
type Parser struct {
	DisableHelpMsgs bool
}

func tokenFromKeyword(k keyword) token {
	return token{
		typ: keywordType,
		val: string(k),
	}
}

func tokenFromSymbol(s symbol) token {
	return token{
		typ: symbolType,
		val: string(s),
	}
}

func expectToken(tokens []*token, cursor uint, t token) bool {
	if cursor >= uint(len(tokens)) {
		return false
	}

	return t.equals(tokens[cursor])
}

func parseToken(tokens []*token, initialCursor uint, typ tokenType) (*token, uint, bool) {
	cursor := initialCursor

	if cursor >= uint(len(tokens)) {
		return nil, initialCursor, false
	}

	current := tokens[initialCursor]
	if current.typ == typ {
		return current, cursor + 1, true
	}

	return nil, initialCursor, false
}

func helpMessage(tokens []*token, cursor uint, msg string) {
	var c *token
	if cursor < uint(len(tokens)) {
		c = tokens[cursor]
	} else {
		c = tokens[cursor-1]
	}

	fmt.Printf("[%d,%d]: %s, got: %s\n", c.loc.line, c.loc.col, msg, c.val)
}

// Parse parses the tokens generated by the lexer and generates and AST
func Parse(source string) (*Ast, error) {
	tokens, err := lex(source)
	if err != nil {
		return nil, err
	}

	a := Ast{}
	cursor := uint(0)
	for cursor < uint(len(tokens)) {
		stmt, newCursor, ok := parseStatement(tokens, cursor, tokenFromSymbol(semicolonSymbol))
		if !ok {
			helpMessage(tokens, cursor, "Expected statement")
			return nil, errors.New("Failed to parse, expected statement")
		}
		cursor = newCursor

		a.Statements = append(a.Statements, stmt)

		atLeastOneSemicolon := false
		for expectToken(tokens, cursor, tokenFromSymbol(semicolonSymbol)) {
			cursor++
			atLeastOneSemicolon = true
		}

		if !atLeastOneSemicolon {
			helpMessage(tokens, cursor, "Expected semi-colon delimiter between statements")
			return nil, errors.New("Missing semi-colon between statements")
		}
	}

	return &a, nil
}

func parseStatement(tokens []*token, initialCursor uint, delimiter token) (*Statement, uint, bool) {
	cursor := initialCursor

	// Look for a SET statement
	semicolonToken := tokenFromSymbol(semicolonSymbol)
	set, newCursor, ok := parseSetStatement(tokens, cursor, semicolonToken)
	if ok {
		return &Statement{
			typ:          SetType,
			SetStatement: set,
		}, newCursor, true
	}

	// Look for a GET statement
	get, newCursor, ok := parseGetStatement(tokens, cursor, semicolonToken)
	if ok {
		return &Statement{
			typ:          GetType,
			GetStatement: get,
		}, newCursor, true
	}

	// Look for a DELETE statement
	del, newCursor, ok := parseDeleteStatement(tokens, cursor, semicolonToken)
	if ok {
		return &Statement{
			typ:             DeleteType,
			DeleteStatement: del,
		}, newCursor, true
	}

	return nil, initialCursor, false
}

func parseSetStatement(tokens []*token, initialCursor uint, delimiter token) (*SetStatement, uint, bool) {
	// SET <key> <value> [expiry] [TODO: ADD COMPLEX EXPRESSIONS SUPPORT]
	cursor := initialCursor

	// Look for the SET keyword
	if !expectToken(tokens, cursor, tokenFromKeyword(setKeyword)) {
		return nil, initialCursor, false
	}
	cursor++

	// Look for the key name
	key, newCursor, ok := parseToken(tokens, cursor, identifierType)
	if !ok {
		helpMessage(tokens, cursor, "Expected a key name")
		return nil, initialCursor, false
	}
	cursor = newCursor

	// Look for the value
	val, newCursor, ok := parseExpression(tokens, cursor)
	if !ok {
		helpMessage(tokens, cursor, "Expected a value")
		return nil, initialCursor, false
	}
	cursor = newCursor

	// Search for optional expiry
	exp, newCursor, ok := parseToken(tokens, cursor, numericType)
	if !ok {
		return &SetStatement{
			key: key.val,
			val: val.val,
		}, cursor, true
	}

	expVal, err := strconv.ParseUint(exp.val, 10, 32)
	if err != nil {
		helpMessage(tokens, cursor, "Invalid expiry provided")
		return nil, cursor, false
	}
	cursor = newCursor

	return &SetStatement{key.val, val.val, uint(expVal)}, cursor, true
}

func parseGetStatement(tokens []*token, initialCursor uint, delimiter token) (*GetStatement, uint, bool) {
	// GET key1 key2 ...
	cursor := initialCursor

	// Look for the GET keyword
	if !expectToken(tokens, cursor, tokenFromKeyword(getKeyword)) {
		return nil, initialCursor, false
	}
	cursor++

	keys := []string{}

	for {
		key, newCursor, ok := parseToken(tokens, cursor, identifierType)
		if !ok {
			// Check if the token is semicolon
			if !expectToken(tokens, newCursor, tokenFromSymbol(semicolonSymbol)) {
				helpMessage(tokens, cursor, "Invalid key name")
				return nil, newCursor, false
			}

			return &GetStatement{keys}, cursor, true
		}

		keys = append(keys, key.val)
		cursor = newCursor
	}
}

func parseDeleteStatement(tokens []*token, initialCursor uint, delimiter token) (*DeleteStatement, uint, bool) {
	// DEL key1 key2 ...
	cursor := initialCursor

	// Look for the DEL keyword
	if !expectToken(tokens, cursor, tokenFromKeyword(delKeyword)) {
		return nil, initialCursor, false
	}
	cursor++

	keys := []string{}

	for {
		key, newCursor, ok := parseToken(tokens, cursor, identifierType)
		if !ok {
			// Check if the token is semicolon
			if !expectToken(tokens, newCursor, tokenFromSymbol(semicolonSymbol)) {
				helpMessage(tokens, cursor, "Invalid key name")
				return nil, newCursor, false
			}

			return &DeleteStatement{keys}, cursor, true
		}

		keys = append(keys, key.val)
		cursor = newCursor
	}
}

func parseExpression(tokens []*token, initialCursor uint) (*token, uint, bool) {
	cursor := initialCursor

	types := []tokenType{identifierType, numericType, stringType}
	for _, typ := range types {
		t, newCursor, ok := parseToken(tokens, cursor, typ)
		if ok {
			return t, newCursor, true
		}
	}

	return nil, initialCursor, false
}
